export type CatalogProduct = {
  product_name: string;
  price: number;
  quantity: number | null;
};

export const productCatalog: CatalogProduct[] = [
  { product_name: "Vitamin C Tablet", price: 70, quantity: 2 },
  { product_name: "Anti Aging Drip Infusion", price: 850, quantity: null },
  { product_name: "Ultra Whitening Skin (Glutathione)", price: 180, quantity: 2 },
  { product_name: "Hip Booster", price: 300, quantity: 8 },
  { product_name: "Stretch Mark Scrub Big", price: 80, quantity: 1 },
  { product_name: "Tripple B Hip Serum", price: 85, quantity: 1 },
  { product_name: "Eyebrow", price: 30, quantity: null },
  { product_name: "Butt Booty Gummies", price: 150, quantity: 1 },
  { product_name: "Grittering Coffee Scrub", price: 100, quantity: 17 },
  { product_name: "Signature Facial", price: 500, quantity: null },
  { product_name: "Body Polish", price: 400, quantity: null },
  { product_name: "Sauna", price: 350, quantity: null },
  { product_name: "Organic Body Scrub", price: 400, quantity: -1 },
  { product_name: "Black Soap Big", price: 100, quantity: 4 },
  { product_name: "PRP stretch marks removal", price: 3000, quantity: null },
  { product_name: "POD Thread (Face Lift)", price: 3000, quantity: null },
  { product_name: "Slim Smart", price: 200, quantity: 1 },
  { product_name: "BBL INJECTIONS 300ML", price: 17500, quantity: null },
  { product_name: "Bikini", price: 150, quantity: -1 },
  { product_name: "Black Soap Small Size", price: 85, quantity: 8 },
  { product_name: "Safi Natural Product", price: 200, quantity: 13 },
  { product_name: "Nose", price: 30, quantity: null },
  { product_name: "Cavitation + Wood Therapy", price: 350, quantity: -1 },
  { product_name: "Stretch Mark Removal Oil", price: 50, quantity: 6 },
  { product_name: "Micro needling stretch marks", price: 300, quantity: null },
  { product_name: "Hip cream", price: 170, quantity: 1 },
  { product_name: "24 Carti Face Cream", price: 120, quantity: 2 },
  { product_name: "Hat tummy tea moringa", price: 170, quantity: 2 },
  { product_name: "BBL INJECTIONS 500ML", price: 25000, quantity: null },
  { product_name: "Ampit", price: 80, quantity: -1 },
  { product_name: "Body Polish", price: 350, quantity: null },
  { product_name: "Face Serum", price: 50, quantity: 5 },
  { product_name: "Breast and Butt Enlargement (Four Sessions)", price: 1000, quantity: null },
  { product_name: "Full Arm", price: 150, quantity: null },
  { product_name: "Dark Nakel Cream", price: 50, quantity: 5 },
  { product_name: "Coffee Body Scrub", price: 450, quantity: -1 },
  { product_name: "Breast and Butt Enlargement Two Sessions", price: 550, quantity: null },
  { product_name: "Head and Neck Massage", price: 180, quantity: null },
  { product_name: "Vitamin C 100 Mg", price: 150, quantity: 5 },
  { product_name: "Skin Whitening Vitamin Gunnies", price: 150, quantity: 0 },
  { product_name: "Sunscreen", price: 150, quantity: 7 },
  { product_name: "Anti Aging Tablet", price: 150, quantity: 2 },
  { product_name: "Breast and Butt Enlargement (Five Sessions)", price: 1200, quantity: null },
  { product_name: "Micro Needing", price: 600, quantity: null },
  { product_name: "BBL INJECTIONS 120ML", price: 7800, quantity: null },
  { product_name: "7D", price: 350, quantity: 4 },
  { product_name: "Keloid Removal", price: 350, quantity: null },
  { product_name: "Hip oil", price: 150, quantity: 2 },
  { product_name: "Derma Planing", price: 350, quantity: null },
  { product_name: "Face Scrub", price: 50, quantity: 8 },
  { product_name: "Skin Whitening Infusion", price: 850, quantity: -2 },
  { product_name: "Couple Massage", price: 700, quantity: null },
  { product_name: "Dark knuckla", price: 150, quantity: 1 },
  { product_name: "Super Fat Burning", price: 150, quantity: 1 },
  { product_name: "Skin Whitening Tablet", price: 150, quantity: 3 },
  { product_name: "Deep tissue massage", price: 400, quantity: -2 },
  { product_name: "Weight Belly Capsules", price: 170, quantity: 1 },
  { product_name: "Face Soap", price: 35, quantity: 10 },
  { product_name: "Anti Pimples Small", price: 50, quantity: 9 },
  { product_name: "Fat Dissolving Inj", price: 750, quantity: -1 },
  { product_name: "BBL INJECTIONS 240ML", price: 14000, quantity: null },
  { product_name: "Maca Butt Enlargement", price: 150, quantity: 3 },
  { product_name: "Mini Facial", price: 200, quantity: null },
  { product_name: "28 Days Detox", price: 150, quantity: 1 },
  { product_name: "Vajacial", price: 250, quantity: null },
  { product_name: "Breast and Butt Enlargement (Per Session)", price: 300, quantity: null },
  { product_name: "Deep Cleansing", price: 350, quantity: null },
  { product_name: "Breast Enlargement Cream", price: 200, quantity: 2 },
  { product_name: "Slimming Pen", price: 1500, quantity: null },
  { product_name: "Slim plus Bruner", price: 150, quantity: 2 },
  { product_name: "Skin Booster Injection", price: 1000, quantity: null },
  { product_name: "BBL Injections 60ml", price: 4000, quantity: null },
  { product_name: "General Body Weight Loss inj.", price: 1350, quantity: null },
  { product_name: "Chest", price: 180, quantity: null },
  { product_name: "Scar removal", price: 450, quantity: null },
  { product_name: "Service add", price: 10, quantity: null },
  { product_name: "Odogu Whitening IV", price: 1500, quantity: null },
  { product_name: "Skin Whitening", price: 150, quantity: 1 },
  { product_name: "Brazilian Wax", price: 200, quantity: null },
  { product_name: "Fruit Body Scrub", price: 350, quantity: null },
  { product_name: "GLUTA WHITE 15000 MG", price: 150, quantity: 1 },
  { product_name: "Breat and Butt Enlargement (Three Sessions)", price: 800, quantity: null },
  { product_name: "Vitamin C IV Infusion", price: 700, quantity: null },
  { product_name: "BBL INJECTIONS 400ML", price: 22000, quantity: null },
  { product_name: "Anti pimples face cleanser", price: 50, quantity: 7 },
  { product_name: "Collagen Drink Ageless", price: 400, quantity: 2 },
  { product_name: "Face mask clay", price: 50, quantity: 4 },
  { product_name: "Chin", price: 70, quantity: null },
  { product_name: "Bathing Gloves", price: 40, quantity: 11 },
  { product_name: "Stretch Marks Scrub Small", price: 60, quantity: 7 },
  { product_name: "Acne Facial", price: 400, quantity: -1 },
  { product_name: "Swedish", price: 350, quantity: -1 },
  { product_name: "BBL INJECTIONS 180ml", price: 11500, quantity: null },
  { product_name: "Slim Plus Fat Burner", price: 150, quantity: 0 },
  { product_name: "Pinsple Cream", price: 60, quantity: 5 },
  { product_name: "Hot Stone", price: 300, quantity: null },
  { product_name: "Anti-aging Facial", price: 350, quantity: null },
  { product_name: "10 Days Slim Detox", price: 300, quantity: 1 },
  { product_name: "Bamboo", price: 250, quantity: null },
  { product_name: "Weight Control Capsules", price: 150, quantity: 1 },
  { product_name: "Deep Tissue", price: 400, quantity: null },
  { product_name: "Skin whitening glutathione", price: 150, quantity: 2 },
  { product_name: "Teeth Whitening", price: 50, quantity: null },
  { product_name: "Gluta Berry 20000 MG", price: 150, quantity: 4 },
  { product_name: "Lipo 6", price: 350, quantity: 2 },
  { product_name: "Black Soap Shower Gel", price: 120, quantity: 3 },
  { product_name: "Whitening Body Scrub", price: 500, quantity: -1 },
  { product_name: "Full Leg", price: 150, quantity: null },
  { product_name: "Back Massage", price: 180, quantity: null },
  { product_name: "Dark Nakel", price: 80, quantity: 6 },
  { product_name: "Caffee Body Scrub", price: 100, quantity: 15 },
  { product_name: "Skin Lightening Infusion", price: 1200, quantity: null },
  { product_name: "Coseit", price: 100, quantity: 3 },
  { product_name: "Body Curve", price: 150, quantity: 2 },
  { product_name: "Body Wrap", price: 400, quantity: null },
  { product_name: "My Moment Face Set", price: 751, quantity: 1 },
  { product_name: "Weight Gain Infusion", price: 750, quantity: null },
  { product_name: "Anti Pimples Face Soap Big", price: 70, quantity: 3 },
  { product_name: "Skin Tag Removal", price: 200, quantity: null },
  { product_name: "Face mask", price: 10, quantity: 125 },
];
