export type CatalogProduct = {
  name: string;
  price: number;
  quantity: number | null;
  image: string;
};

export const productCatalog: Record<string, CatalogProduct> = {
  product_001: { name: "Vitamin C Tablet", price: 70, quantity: 2, image: "/products/8.jpeg" },
  product_002: { name: "Anti Aging Drip Infusion", price: 850, quantity: null, image: "/products/17.jpeg" },
  product_003: { name: "Ultra Whitening Skin (Glutathione)", price: 180, quantity: 2, image: "/products/7.jpeg" },
  product_004: { name: "Hip Booster", price: 300, quantity: 8, image: "/products/2.jpeg" },
  product_005: { name: "Stretch Mark Scrub Big", price: 80, quantity: 1, image: "/products/11.jpeg" },
  product_006: { name: "Tripple B Hip Serum", price: 85, quantity: 1, image: "/products/2.jpeg" },
  product_007: { name: "Eyebrow", price: 30, quantity: null, image: "/products/16.jpeg" },
  product_008: { name: "Butt Booty Gummies", price: 150, quantity: 1, image: "/products/2.jpeg" },
  product_009: { name: "Glittering Coffee Scrub", price: 100, quantity: 17, image: "/products/17.jpeg" },
  product_010: { name: "Signature Facial", price: 500, quantity: null, image: "/products/14.jpeg" },
  product_011: { name: "Body Polish", price: 400, quantity: null, image: "/products/11.jpeg" },
  product_012: { name: "Sauna", price: 350, quantity: null, image: "/products/18.jpeg" },
  product_013: { name: "Organic Body Scrub", price: 400, quantity: -1, image: "/products/20.jpeg" },
  product_014: { name: "Black Soap Big", price: 100, quantity: 4, image: "/products/10.jpeg" },
  product_015: { name: "PRP stretch marks removal", price: 3000, quantity: null, image: "/products/18.jpeg" },
  product_016: { name: "POD Thread (Face Lift)", price: 3000, quantity: null, image: "/products/18.jpeg" },
  product_017: { name: "Slim Smart", price: 200, quantity: 1, image: "/products/4.jpeg" },
  product_018: { name: "BBL INJECTIONS 300ML", price: 17500, quantity: null, image: "/products/2.jpeg" },
  product_019: { name: "Bikini", price: 150, quantity: -1, image: "/products/16.jpeg" },
  product_020: { name: "Black Soap Small Size", price: 85, quantity: 8, image: "/products/10.jpeg" },
  product_021: { name: "Safi Natural Product", price: 200, quantity: 13, image: "/products/16.jpeg" },
  product_022: { name: "Nose", price: 30, quantity: null, image: "/products/16.jpeg" },
  product_023: { name: "Cavitation + Wood Therapy", price: 350, quantity: -1, image: "/products/18.jpeg" },
  product_024: { name: "Stretch Mark Removal Oil", price: 50, quantity: 6, image: "/products/12.jpeg" },
  product_025: { name: "Micro needling stretch marks", price: 300, quantity: null, image: "/products/14.jpeg" },
  product_026: { name: "Hip cream", price: 170, quantity: 1, image: "/products/2.jpeg" },
  product_027: { name: "24 Carti Face Cream", price: 120, quantity: 2, image: "/products/12.jpeg" },
  product_028: { name: "Hat tummy tea moringa", price: 170, quantity: 2, image: "/products/4.jpeg" },
  product_029: { name: "BBL INJECTIONS 500ML", price: 25000, quantity: null, image: "/products/2.jpeg" },
  product_030: { name: "Ampit", price: 80, quantity: -1, image: "/products/18.jpeg" },
  product_031: { name: "Body Polish", price: 350, quantity: null, image: "/products/11.jpeg" },
  product_032: { name: "Face Serum", price: 50, quantity: 5, image: "/products/12.jpeg" },
  product_033: { name: "Breast and Butt Enlargement (Four Sessions)", price: 1000, quantity: null, image: "/products/2.jpeg" },
  product_034: { name: "Full Arm", price: 150, quantity: null, image: "/products/16.jpeg" },
  product_035: { name: "Dark Nakel Cream", price: 50, quantity: 5, image: "/products/12.jpeg" },
  product_036: { name: "Coffee Body Scrub", price: 450, quantity: -1, image: "/products/11.jpeg" },
  product_037: { name: "Breast and Butt Enlargement Two Sessions", price: 550, quantity: null, image: "/products/2.jpeg" },
  product_038: { name: "Head and Neck Massage", price: 180, quantity: null, image: "/products/15.jpeg" },
  product_039: { name: "Vitamin C 100 Mg", price: 150, quantity: 5, image: "/products/9.jpeg" },
  product_040: { name: "Skin Whitening Vitamin Gunnies", price: 150, quantity: 0, image: "/products/13.jpeg" },
  product_041: { name: "Sunscreen", price: 150, quantity: 7, image: "/products/9.jpeg" },
  product_042: { name: "Anti Aging Tablet", price: 150, quantity: 2, image: "/products/9.jpeg" },
  product_043: { name: "Breast and Butt Enlargement (Five Sessions)", price: 1200, quantity: null, image: "/products/2.jpeg" },
  product_044: { name: "Micro Needing", price: 600, quantity: null, image: "/products/14.jpeg" },
  product_045: { name: "BBL INJECTIONS 120ML", price: 7800, quantity: null, image: "/products/2.jpeg" },
  product_046: { name: "7D", price: 350, quantity: 4, image: "/products/18.jpeg" },
  product_047: { name: "Keloid Removal", price: 350, quantity: null, image: "/products/18.jpeg" },
  product_048: { name: "Hip oil", price: 150, quantity: 2, image: "/products/2.jpeg" },
  product_049: { name: "Derma Planing", price: 350, quantity: null, image: "/products/14.jpeg" },
  product_050: { name: "Face Scrub", price: 50, quantity: 8, image: "/products/11.jpeg" },
  product_051: { name: "Skin Whitening Infusion", price: 850, quantity: -2, image: "/products/7.jpeg" },
  product_052: { name: "Couple Massage", price: 700, quantity: null, image: "/products/15.jpeg" },
  product_053: { name: "Dark knuckla", price: 150, quantity: 1, image: "/products/18.jpeg" },
  product_054: { name: "Super Fat Burning", price: 150, quantity: 1, image: "/products/18.jpeg" },
  product_055: { name: "Skin Whitening Tablet", price: 150, quantity: 3, image: "/products/9.jpeg" },
  product_056: { name: "Deep tissue massage", price: 400, quantity: -2, image: "/products/15.jpeg" },
  product_057: { name: "Weight Belly Capsules", price: 170, quantity: 1, image: "/products/4.jpeg" },
  product_058: { name: "Face Soap", price: 35, quantity: 10, image: "/products/10.jpeg" },
  product_059: { name: "Anti Pimples Small", price: 50, quantity: 9, image: "/products/18.jpeg" },
  product_060: { name: "Fat Dissolving Inj", price: 750, quantity: -1, image: "/products/17.jpeg" },
  product_061: { name: "BBL INJECTIONS 240ML", price: 14000, quantity: null, image: "/products/2.jpeg" },
  product_062: { name: "Maca Butt Enlargement", price: 150, quantity: 3, image: "/products/3.jpeg" },
  product_063: { name: "Mini Facial", price: 200, quantity: null, image: "/products/14.jpeg" },
  product_064: { name: "28 Days Detox", price: 150, quantity: 1, image: "/products/4.jpeg" },
  product_065: { name: "Vajacial", price: 250, quantity: null, image: "/products/14.jpeg" },
  product_066: { name: "Breast and Butt Enlargement (Per Session)", price: 300, quantity: null, image: "/products/2.jpeg" },
  product_067: { name: "Deep Cleansing", price: 350, quantity: null, image: "/products/14.jpeg" },
  product_068: { name: "Breast Enlargement Cream", price: 200, quantity: 2, image: "/products/3.jpeg" },
  product_069: { name: "Slimming Pen", price: 1500, quantity: null, image: "/products/4.jpeg" },
  product_070: { name: "Slim plus Bruner", price: 150, quantity: 2, image: "/products/15.jpeg" },
  product_071: { name: "Skin Booster Injection", price: 1000, quantity: null, image: "/products/17.jpeg" },
  product_072: { name: "BBL Injections 60ml", price: 4000, quantity: null, image: "/products/2.jpeg" },
  product_073: { name: "General Body Weight Loss inj.", price: 1350, quantity: null, image: "/products/4.jpeg" },
  product_074: { name: "Chest", price: 180, quantity: null, image: "/products/16.jpeg" },
  product_075: { name: "Scar removal", price: 450, quantity: null, image: "/products/18.jpeg" },
  product_077: { name: "Odogu Whitening IV", price: 1500, quantity: null, image: "/products/7.jpeg" },
  product_078: { name: "Skin Whitening", price: 150, quantity: 1, image: "/products/7.jpeg" },
  product_079: { name: "Brazilian Wax", price: 200, quantity: null, image: "/products/16.jpeg" },
  product_080: { name: "Fruit Body Scrub", price: 350, quantity: null, image: "/products/11.jpeg" },
  product_081: { name: "GLUTA WHITE 15000 MG", price: 150, quantity: 1, image: "/products/7.jpeg" },
  product_082: { name: "Breat and Butt Enlargement (Three Sessions)", price: 800, quantity: null, image: "/products/2.jpeg" },
  product_083: { name: "Vitamin C IV Infusion", price: 700, quantity: null, image: "/products/9.jpeg" },
  product_084: { name: "BBL INJECTIONS 400ML", price: 22000, quantity: null, image: "/products/2.jpeg" },
  product_085: { name: "Anti pimples face cleanser", price: 50, quantity: 7, image: "/products/10.jpeg" },
  product_086: { name: "Collagen Drink Ageless", price: 400, quantity: 2, image: "/products/18.jpeg" },
  product_087: { name: "Face mask clay", price: 50, quantity: 4, image: "/products/12.jpeg" },
  product_088: { name: "Chin", price: 70, quantity: null, image: "/products/16.jpeg" },
  product_089: { name: "Bathing Gloves", price: 40, quantity: 11, image: "/products/10.jpeg" },
  product_090: { name: "Stretch Marks Scrub Small", price: 60, quantity: 7, image: "/products/11.jpeg" },
  product_091: { name: "Acne Facial", price: 400, quantity: -1, image: "/products/14.jpeg" },
  product_092: { name: "Swedish", price: 350, quantity: -1, image: "/products/15.jpeg" },
  product_093: { name: "BBL INJECTIONS 180ml", price: 11500, quantity: null, image: "/products/2.jpeg" },
  product_094: { name: "Slim Plus Fat Burner", price: 150, quantity: 0, image: "/products/4.jpeg" },
  product_095: { name: "Pinsple Cream", price: 60, quantity: 5, image: "/products/12.jpeg" },
  product_096: { name: "Hot Stone", price: 300, quantity: null, image: "/products/15.jpeg" },
  product_097: { name: "Anti-aging Facial", price: 350, quantity: null, image: "/products/14.jpeg" },
  product_098: { name: "10 Days Slim Detox", price: 300, quantity: 1, image: "/products/4.jpeg" },
  product_099: { name: "Bamboo", price: 250, quantity: null, image: "/products/15.jpeg" },
  product_100: { name: "Weight Control Capsules", price: 150, quantity: 1, image: "/products/4.jpeg" },
  product_101: { name: "Deep Tissue", price: 400, quantity: null, image: "/products/18.jpeg" },
  product_102: { name: "Skin whitening glutathione", price: 150, quantity: 2, image: "/products/7.jpeg" },
  product_103: { name: "Teeth Whitening", price: 50, quantity: null, image: "/products/7.jpeg" },
  product_104: { name: "Gluta Berry 20000 MG", price: 150, quantity: 4, image: "/products/7.jpeg" },
  product_105: { name: "Lipo 6", price: 350, quantity: 2, image: "/products/13.jpeg" },
  product_106: { name: "Black Soap Shower Gel", price: 120, quantity: 3, image: "/products/10.jpeg" },
  product_107: { name: "Whitening Body Scrub", price: 500, quantity: -1, image: "/products/7.jpeg" },
  product_108: { name: "Full Leg", price: 150, quantity: null, image: "/products/16.jpeg" },
  product_109: { name: "Back Massage", price: 180, quantity: null, image: "/products/15.jpeg" },
  product_110: { name: "Dark Nakel", price: 80, quantity: 6, image: "/products/18.jpeg" },
  product_111: { name: "Caffee Body Scrub", price: 100, quantity: 15, image: "/products/18.jpeg" },
  product_112: { name: "Skin Lightening Infusion", price: 1200, quantity: null, image: "/products/7.jpeg" },
  product_113: { name: "Coseit", price: 100, quantity: 3, image: "/products/18.jpeg" },
  product_114: { name: "Body Curve", price: 150, quantity: 2, image: "/products/2.jpeg" },
  product_115: { name: "Body Wrap", price: 400, quantity: null, image: "/products/18.jpeg" },
  product_116: { name: "My Moment Face Set", price: 751, quantity: 1, image: "/products/12.jpeg" },
  product_117: { name: "Weight Gain Infusion", price: 750, quantity: null, image: "/products/4.jpeg" },
  product_118: { name: "Anti Pimples Face Soap Big", price: 70, quantity: 3, image: "/products/10.jpeg" },
  product_119: { name: "Skin Tag Removal", price: 200, quantity: null, image: "/products/18.jpeg" },
  product_120: { name: "Face mask", price: 10, quantity: 125, image: "/products/facemask.jpeg" },
  product_121: { name: "Ultimate Maca Syrup", price: 200, quantity: null, image: "/products/12.jpeg" },
  product_122: { name: "Slim Green Coffee", price: 150, quantity: null, image: "/products/15.jpeg" },
};
